### PR TITLE
Replace tsd with typings and make the module installable for other projects

### PR DESCRIPTION
**Pull request by haadcode**
This PR removes `tsd` dependency and replaces it with `typings`. It will also add needed files to the npm package so that the module can be installed to other projects as per regular npm workflow.

### CODE REVIEW

**Comment by haadcode** [comment]
And tsd seems to deprecated, so replace it with `typings`

**Comment by haadcode** [comment]
Hold off merging this, doesn't seem to be fully working as a dependency in other projects.

**Comment by rmhrisk** [comment]
@haadcode thanks for your help with this, its been on my list to get straightened out along with getting softhsm working in travis; just not enough time in the day. Your awesome thanks and let me know if I can be of help.

**Comment by haadcode** [comment]
Renamed the PR to reflect what it actually does. This should work now.

**Comment by rmhrisk** [comment]
@haadcode looks good to me, can you also update the readme "Installation" section to reflect this change.

**Comment by haadcode** [comment]
Updated

**Comment by rmhrisk** [comment]
@microshine and I spoke, we have decided to redo the package to remove the TS aspects from the NPM and leave the TS stuff in the github repo. He convinced me this is a better approach. We will do that this week after we finish fixing the Travis build issues for our other projects. Thanks for your help.

**Comment by haadcode** [comment]
Sounds good!

**Comment by rmhrisk** [comment]
Change is in now let me kNow if things work for you.

**Pull request closed without merging**
