### PR TITLE
Prepublish

### LINKED ISSUE #50: Support npm install
Make it possible to use `npm install https://github.com/PeculiarVentures/node-webcrypto-ossl.git`

### PR DESCRIPTION
**Pull request by hildjj**
Fixes #50.  To prove: `npm install hildjj/node-webcrypto-ossl#prepublish`
Depends on #71.  Fixes the TODO from there.  I decided #50 was the feature request.

This should also help prevent publishing to npm without having run tsc.

### CODE REVIEW

**Comment by hildjj** [comment]
Wait on merging this one, please.  I want to test more with typescript not installed globally.

**Comment by hildjj** [comment]
I have a couple of options, and need input before declaring #50 fixed.  The issue is that if you don't have typescript and typings installed globally when you npm install from github, the install fails.  Approaches I've thought of so far:

1. Check in the javascript outputs to git.  I know that sounds odd, but it's likely the best choice, and one I've used in other projects.
1. Move typescript and typings from devDependencies to dependencies.  I dislike this, since it means that *everyone* has to install these two dependencies, not just the people installing from github.
1. Make typescript and typings peerDependencies.  This is no better than making them dependencies, with the added hassle of nobody understanding peerDependencies anymore.
1. Do some complicated scripting in the postInstall hook to detect that you're in this state and manually install typescript and typings. This will likely fail on Windows often and will be a hassle to maintain.

I'd like to go with 1, but would really want @rmhrisk and @microshine 's opinions before making such a drastic change to the project.

**Comment by microshine** [comment]
I suggest to use compiled JS for npm publication. Developers who wants to use git version must to have installed globally typescript and typings

**Comment by hildjj** [comment]
@microshine ok, then this PR is good to merge, unless you want a better error message.

**Pull request merged**
